-- stg_clicks.sql

WITH raw_stream AS (
    -- We use the macro to reference the table we defined in sources.yml
    -- This ensures dbt builds the dependency graph correctly.
    SELECT * 
    FROM {{ source('raw_ecommerce', 'raw_clicks') }}
)

SELECT
    -- 1. EXTRACTING METADATA
    -- The metadata contains Kafka routing info. We extract the timestamp when Kafka received the event.
    -- The colon (:) reaches into the JSON, and the double colon (::) casts it to a timestamp.
    TRY_TO_TIMESTAMP(RECORD_METADATA:CreateTime::STRING) AS kafka_received_at,

    -- 2. EXTRACTING PAYLOAD DATA (RECORD_CONTENT)
    -- Here we parse out the fake e-commerce data generated by your Python script.
    
    -- Extract the unique event ID and cast it as a standard string (VARCHAR)
    RECORD_CONTENT:event_id::STRING AS event_id,
    
    -- Extract the user ID and cast it as a string
    RECORD_CONTENT:user_id::STRING AS user_id,
    
    -- Extract the type of event (e.g., 'page_view', 'add_to_cart') and cast as a string
    RECORD_CONTENT:event_type::STRING AS event_type,
    
    -- Extract the product ID and cast as a string
    RECORD_CONTENT:product_id::STRING AS product_id,
    
    -- Extract the price. We cast this as a FLOAT so we can perform math on it later.
    RECORD_CONTENT:price::FLOAT AS price,
    
    -- Extract the device used (e.g., 'mobile', 'desktop') and cast as a string
    RECORD_CONTENT:device::STRING AS device,
    
    -- Extract the IP address and cast as a string
    RECORD_CONTENT:ip_address::STRING AS ip_address,
    
    -- Extract the exact time the user clicked (generated by Python), cast as timestamp
    TRY_TO_TIMESTAMP(RECORD_CONTENT:timestamp::STRING) AS event_created_at

FROM raw_stream

-- Optional: Filter out any completely empty rows just in case Snowpipe ingested a blank record
WHERE RECORD_CONTENT IS NOT NULL