name: dbt CI/CD Data Quality Checks
on: [push, pull_request]

jobs:
  dbt_run_and_test:
    runs-on: ubuntu-latest
    env:
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      DBT_SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - run: pip install dbt-snowflake==1.7.3
      # We define the project dir here once
      - run: dbt deps --project-dir dbt_ecommerce
      - run: dbt compile --project-dir dbt_ecommerce
      - run: dbt test --project-dir dbt_ecommerce